name: Build & Push container image

on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - "**/*.md"
      - "terraform/"
      - "README"
      - "README.*"

env:
  IMAGE_NAME: mdsahiloss/simple-time-service
  IMAGE_TAG: ${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          cd app/
          docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Push Docker image
        run: docker push $IMAGE_NAME:$IMAGE_TAG
